### ISSUE TITLE
Figure rendering and alteration

### ISSUE THREAD

**Issue by abruce91** [Project-Platypus/PRIM#3]
Hi David,

My name is Alexa Bruce and I am a PhD student at UMass Amherst. 

Thanks very much for the PRIM algorithm. Super useful!

I am having some issues with figure rendering - I am not able to interact with the figures as per your example. Both for the tradeoff curve and the box details (Prev and Next do not work)

In addition, I would like to alter the size of the figures so that I can see the Box Coverage plot. 

I have provided some screen shots of my code below for reference.

Thanks!

![image](https://user-images.githubusercontent.com/49037948/56428167-6ae75600-628c-11e9-822d-aa70545949ed.png)
![image](https://user-images.githubusercontent.com/49037948/56428189-86eaf780-628c-11e9-85a4-13dfd17bba9c.png)
![image](https://user-images.githubusercontent.com/49037948/56428222-9ff3a880-628c-11e9-867e-b8b63a2d7074.png)

**Comment by dhadka** [comment]
Hi Alexa.  It looks like you're running this in Jupyter (or another browser-based Python tool).  In order to use the interactive plots, you'll need to run the commands in Python directly.

**Comment by abruce91** [comment]
Thanks very much David! That did it!
