### ISSUE TITLE
Dataframe ix method

### ISSUE THREAD

**Issue by kasra-keshavarz** [Project-Platypus/PRIM#4]
https://github.com/Project-Platypus/PRIM/blob/18dd130814160fceddfb1fd2720e288f4ab6a641/prim/prim_box.py#L514

The `ix `method of pandas.DataFrame has been deprecated in favor of `iloc `an `loc `methods since version 0.20.0.

**Comment by scalet98** [comment]
After I change ix with loc in the code directly, it works well.

**Comment by dhadka** [comment]
Fixed by https://github.com/Project-Platypus/PRIM/pull/7

**Comment by SiegfriedBeier** [comment]
in [PRIM](https://github.com/Project-Platypus/PRIM/tree/master)/[prim](https://github.com/Project-Platypus/PRIM/tree/master/prim)

/prim_box.py
Line 558
` label = self.peeling_trajectory.ix[[i], columns_to_include]` 

pandas .ix method is deprecated, as mentioned in first comment
