### ISSUE TITLE
Package does not work with matplotlib > 3.3

### ISSUE THREAD

**Issue by willu47** [Project-Platypus/PRIM#6]
`set_window_title` was deprecated in matplotlib 3.4.

Either:

- constrain version of matplotlib < 3.4

Or:

- fix bug e.g. update `set_window_title` (the same issue is listed [here](https://github.com/raysect/source/issues/383))

**Comment by dhadka** [comment]
Fixed by https://github.com/Project-Platypus/PRIM/pull/7
